const fs = require("fs");
const file = "C:/Users/viana/BRAZILFIT/backend/src/routes/checkins.js";
let lines = fs.readFileSync(file, "utf8").split("\n");
lines[98] = "        wins || null,";
lines[112] = "        today,";
lines[113] = "        new Date().toISOString(),";
lines[114] = "        existing.id";
lines[133] = "        what_was_challenging || null,";
lines[149] = "    );";
lines[150] = "    res.json({ id: result.lastInsertRowid, message: \"Check-in submitted\" });";
fs.writeFileSync(file, lines.join("\n"), "utf8");
console.log("Done");
