// All 100 meals with Unsplash photo URLs (4 categories, 25 meals each)

const MEALS_DATA = [
  // MUSCLE GAIN - 25 meals
  { name: 'Overnight Oats with Banana', calories: 380, goal: 'muscle-gain', emoji: '🥣', description: 'Oats, banana, almond milk, chia seeds, honey. Prep the night before for an easy performance breakfast.', photo_keyword: 'overnight-oats' },
  { name: 'Grilled Chicken and Sweet Potato', calories: 520, goal: 'muscle-gain', emoji: '🍗', description: 'Lean protein with complex carbs. Season with paprika and herbs. Perfect post-training recovery meal.', photo_keyword: 'grilled-chicken' },
  { name: 'Salmon and Brown Rice', calories: 490, goal: 'muscle-gain', emoji: '🐟', description: 'Omega-3 rich salmon with complete protein. Add steamed vegetables for micronutrients.', photo_keyword: 'salmon-rice' },
  { name: 'Greek Yoghurt with Berries', calories: 290, goal: 'muscle-gain', emoji: '🥛', description: 'Full-fat Greek yoghurt with mixed berries and walnuts. High-protein snack option.', photo_keyword: 'greek-yoghurt' },
  { name: 'Egg White Omelette', calories: 220, goal: 'muscle-gain', emoji: '🍳', description: '6 egg whites with spinach, mushrooms and tomatoes. Lean protein breakfast powerhouse.', photo_keyword: 'omelette-eggs' },
  { name: 'Tuna and Avocado Toast', calories: 410, goal: 'muscle-gain', emoji: '🍞', description: 'Canned tuna on wholegrain toast with avocado slices. Quick protein-rich lunch.', photo_keyword: 'avocado-toast' },
  { name: 'Cottage Cheese and Pineapple', calories: 250, goal: 'muscle-gain', emoji: '🍍', description: 'High-protein dairy with fresh pineapple. Perfect post-workout snack.', photo_keyword: 'cottage-cheese' },
  { name: 'Beef Stir Fry with Noodles', calories: 580, goal: 'muscle-gain', emoji: '🍜', description: 'Lean beef with mixed vegetables and brown rice noodles. Complete meal with carbs and protein.', photo_keyword: 'beef-stir-fry' },
  { name: 'Protein Pancakes', calories: 340, goal: 'muscle-gain', emoji: '🥞', description: 'Made with whey protein powder, oats and eggs. Top with Greek yoghurt and berries.', photo_keyword: 'pancakes-healthy' },
  { name: 'Turkey and Quinoa Bowl', calories: 460, goal: 'muscle-gain', emoji: '🍲', description: 'Ground turkey with complete protein quinoa and roasted vegetables.', photo_keyword: 'quinoa-bowl' },
  { name: 'Chicken and Broccoli', calories: 380, goal: 'muscle-gain', emoji: '🥦', description: 'Grilled chicken breast with steamed broccoli and brown rice. Classic muscle-building meal.', photo_keyword: 'chicken-broccoli' },
  { name: 'Lentil and Spinach Curry', calories: 420, goal: 'muscle-gain', emoji: '🍛', description: 'Plant-based protein from lentils with iron-rich spinach. Serve with basmati rice.', photo_keyword: 'lentil-curry' },
  { name: 'Steak and Roasted Vegetables', calories: 550, goal: 'muscle-gain', emoji: '🥩', description: 'Grass-fed sirloin with sweet potato, broccoli and carrots. Iron and nutrient-dense.', photo_keyword: 'steak-vegetables' },
  { name: 'Tuna Pasta', calories: 480, goal: 'muscle-gain', emoji: '🍝', description: 'Whole wheat pasta with canned tuna, olive oil and fresh herbs. Protein and carbs.', photo_keyword: 'tuna-pasta' },
  { name: 'Black Bean Burrito Bowl', calories: 510, goal: 'muscle-gain', emoji: '🌯', description: 'Black beans, brown rice, corn, avocado, Greek yoghurt. Complete plant-based protein.', photo_keyword: 'burrito-bowl' },
  { name: 'Smoked Salmon Bagel', calories: 440, goal: 'muscle-gain', emoji: '🥯', description: 'Wholegrain bagel with smoked salmon, cream cheese and capers. Omega-3 rich.', photo_keyword: 'smoked-salmon-bagel' },
  { name: 'Chicken Caesar Salad', calories: 390, goal: 'muscle-gain', emoji: '🥗', description: 'Grilled chicken with cos lettuce, parmesan and light Caesar dressing. Balanced meal.', photo_keyword: 'caesar-salad' },
  { name: 'Edamame and Rice Bowl', calories: 370, goal: 'muscle-gain', emoji: '🍚', description: 'Cooked edamame with white rice and stir-fried vegetables. Plant-based complete protein.', photo_keyword: 'edamame-rice' },
  { name: 'Peanut Butter and Banana Smoothie', calories: 320, goal: 'muscle-gain', emoji: '🥤', description: 'Peanut butter, banana, milk and protein powder. Sweet and satisfying.', photo_keyword: 'peanut-butter-smoothie' },
  { name: 'Beef and Vegetable Soup', calories: 340, goal: 'muscle-gain', emoji: '🍲', description: 'Lean beef with carrots, celery, onions and barley. Warming muscle-building soup.', photo_keyword: 'beef-soup' },
  { name: 'Scrambled Eggs on Sourdough', calories: 380, goal: 'muscle-gain', emoji: '🍳', description: '4 scrambled eggs on toasted sourdough with butter. Simple protein breakfast.', photo_keyword: 'scrambled-eggs-toast' },
  { name: 'Chicken Tikka with Rice', calories: 520, goal: 'muscle-gain', emoji: '🍛', description: 'Marinated and spiced chicken with basmati rice. Flavorful and protein-rich.', photo_keyword: 'chicken-tikka' },
  { name: 'Prawn and Avocado Salad', calories: 310, goal: 'muscle-gain', emoji: '🦐', description: 'Grilled prawns with fresh avocado, mixed leaves and lemon. Lean protein seafood.', photo_keyword: 'prawn-salad' },
  { name: 'Whey Protein Smoothie Bowl', calories: 350, goal: 'muscle-gain', emoji: '🥣', description: 'Thick protein smoothie topped with granola and berries. Post-workout winner.', photo_keyword: 'smoothie-bowl' },
  { name: 'Mozzarella and Tomato with Chicken', calories: 430, goal: 'muscle-gain', emoji: '🍅', description: 'Grilled chicken with fresh mozzarella, tomato and basil. Caprese-style protein meal.', photo_keyword: 'caprese-chicken' },

  // WEIGHT LOSS - 25 meals
  { name: 'Grilled Fish and Steamed Vegetables', calories: 280, goal: 'weight-loss', emoji: '🐟', description: 'White fish fillet with broccoli, carrots and green beans. Zero-guilt meal.', photo_keyword: 'grilled-fish-vegetables' },
  { name: 'Chicken and Vegetable Soup', calories: 220, goal: 'weight-loss', emoji: '🍲', description: 'Lean chicken with mixed vegetables in low-fat broth. Filling and low-calorie.', photo_keyword: 'chicken-vegetable-soup' },
  { name: 'Zucchini Noodles with Tomato Sauce', calories: 190, goal: 'weight-loss', emoji: '🍝', description: 'Spiralized zucchini with fresh tomato sauce and lean meat. Low-carb pasta alternative.', photo_keyword: 'zucchini-noodles' },
  { name: 'Green Smoothie', calories: 180, goal: 'weight-loss', emoji: '🥤', description: 'Spinach, banana, protein powder, almond milk. Nutrient-dense breakfast drink.', photo_keyword: 'green-smoothie' },
  { name: 'Cauliflower Rice Bowl', calories: 240, goal: 'weight-loss', emoji: '🥦', description: 'Riced cauliflower with stir-fried vegetables and lean protein. Low-carb rice alternative.', photo_keyword: 'cauliflower-rice' },
  { name: 'Lettuce Wrap Tacos', calories: 260, goal: 'weight-loss', emoji: '🥬', description: 'Lean ground turkey in lettuce wraps with tomato, onion and salsa. Carb-free tacos.', photo_keyword: 'lettuce-wrap' },
  { name: 'Cucumber and Hummus', calories: 160, goal: 'weight-loss', emoji: '🥒', description: 'Fresh cucumber slices with light hummus dip. Refreshing low-calorie snack.', photo_keyword: 'hummus-vegetables' },
  { name: 'Poached Eggs and Spinach', calories: 210, goal: 'weight-loss', emoji: '🍳', description: '2 poached eggs on wilted spinach with wholemeal toast. Protein-rich breakfast.', photo_keyword: 'poached-eggs-spinach' },
  { name: 'Watermelon and Feta Salad', calories: 190, goal: 'weight-loss', emoji: '🍉', description: 'Fresh watermelon with feta cheese and mint. Summer weight-loss salad.', photo_keyword: 'watermelon-feta' },
  { name: 'Turkey Lettuce Cups', calories: 240, goal: 'weight-loss', emoji: '🥬', description: 'Ground turkey with asian flavors in lettuce leaves. Light and satisfying.', photo_keyword: 'turkey-lettuce' },
  { name: 'Baked Cod with Lemon', calories: 230, goal: 'weight-loss', emoji: '🐟', description: 'White fish with lemon, herbs and steamed asparagus. Clean protein meal.', photo_keyword: 'baked-cod' },
  { name: 'Tomato and Basil Soup', calories: 150, goal: 'weight-loss', emoji: '🍅', description: 'Fresh tomato soup with basil and light cream. Warming low-calorie classic.', photo_keyword: 'tomato-soup' },
  { name: 'Courgette and Egg Frittata', calories: 270, goal: 'weight-loss', emoji: '🍳', description: 'Baked eggs with courgette, mushrooms and peppers. Protein-packed vegetable dish.', photo_keyword: 'frittata' },
  { name: 'Tuna Stuffed Peppers', calories: 250, goal: 'weight-loss', emoji: '🫑', description: 'Bell peppers filled with canned tuna, brown rice and herbs. Colorful low-calorie meal.', photo_keyword: 'stuffed-peppers' },
  { name: 'Berry and Kale Smoothie', calories: 170, goal: 'weight-loss', emoji: '🫐', description: 'Kale, mixed berries, protein powder and almond milk. Antioxidant weight-loss drink.', photo_keyword: 'berry-kale-smoothie' },
  { name: 'Grilled Asparagus and Salmon', calories: 290, goal: 'weight-loss', emoji: '🦐', description: 'Grilled salmon fillet with roasted asparagus and lemon. Omega-3 rich light meal.', photo_keyword: 'asparagus-salmon' },
  { name: 'Cucumber Sushi Rolls', calories: 200, goal: 'weight-loss', emoji: '🍣', description: 'Cucumber wrapped with crab stick and avocado. Low-carb sushi alternative.', photo_keyword: 'sushi-rolls' },
  { name: 'Mushroom and Spinach Omelette', calories: 220, goal: 'weight-loss', emoji: '🍳', description: '3 eggs with sautéed mushrooms and spinach. Quick protein breakfast.', photo_keyword: 'mushroom-omelette' },
  { name: 'Apple and Almond Butter', calories: 210, goal: 'weight-loss', emoji: '🍎', description: 'Sliced apple with natural almond butter. Balanced healthy snack.', photo_keyword: 'apple-almond-butter' },
  { name: 'Grilled Prawns and Salad', calories: 240, goal: 'weight-loss', emoji: '🦐', description: 'Grilled prawns on mixed greens with lemon dressing. Lean protein salad.', photo_keyword: 'grilled-prawns-salad' },
  { name: 'Vegetable Broth Soup', calories: 120, goal: 'weight-loss', emoji: '🥣', description: 'Light vegetable broth with carrots, celery and herbs. Ultra-low calorie warm drink.', photo_keyword: 'vegetable-broth' },
  { name: 'Baked Sweet Potato', calories: 180, goal: 'weight-loss', emoji: '🥔', description: 'Medium sweet potato baked plain. Satisfying complex carbs.', photo_keyword: 'baked-sweet-potato' },
  { name: 'Mango and Prawn Salad', calories: 260, goal: 'weight-loss', emoji: '🥭', description: 'Grilled prawns with fresh mango, mixed leaves and ginger dressing. Tropical light meal.', photo_keyword: 'mango-prawn-salad' },
  { name: 'Ratatouille', calories: 200, goal: 'weight-loss', emoji: '🍆', description: 'Roasted eggplant, zucchini, peppers and tomatoes. Mediterranean vegetable dish.', photo_keyword: 'ratatouille' },
  { name: 'Chia Pudding', calories: 230, goal: 'weight-loss', emoji: '🥣', description: 'Chia seeds with almond milk and berries. High in fiber and protein.', photo_keyword: 'chia-pudding' },

  // RECOVERY - 25 meals
  { name: 'Salmon and Quinoa', calories: 490, goal: 'recovery', emoji: '🐟', description: 'Omega-3 rich salmon with complete protein quinoa. Anti-inflammatory powerhouse.', photo_keyword: 'salmon-quinoa' },
  { name: 'Cherry and Almond Smoothie', calories: 290, goal: 'recovery', emoji: '🍒', description: 'Tart cherry juice, almonds and protein powder. Recovery and muscle repair drink.', photo_keyword: 'cherry-smoothie' },
  { name: 'Turmeric Golden Milk', calories: 180, goal: 'recovery', emoji: '☕', description: 'Warm oat milk with turmeric, ginger and honey. Anti-inflammatory evening drink.', photo_keyword: 'turmeric-milk' },
  { name: 'Sweet Potato and Black Bean Bowl', calories: 420, goal: 'recovery', emoji: '🍠', description: 'Roasted sweet potato with black beans and spinach. Recovery-focused plant meal.', photo_keyword: 'sweet-potato-black-bean' },
  { name: 'Chicken Bone Broth Soup', calories: 210, goal: 'recovery', emoji: '🍲', description: 'Slow-cooked bone broth with collagen for joint recovery. Healing warm meal.', photo_keyword: 'bone-broth-soup' },
  { name: 'Blueberry Protein Smoothie', calories: 310, goal: 'recovery', emoji: '🫐', description: 'Blueberries, protein powder, Greek yoghurt and honey. Antioxidant recovery drink.', photo_keyword: 'blueberry-smoothie' },
  { name: 'Avocado and Egg Toast', calories: 380, goal: 'recovery', emoji: '🥑', description: 'Poached eggs on sourdough with ripe avocado. Recovery meal with healthy fats.', photo_keyword: 'avocado-egg-toast' },
  { name: 'Omega-3 Sardine Toast', calories: 320, goal: 'recovery', emoji: '🐟', description: 'Canned sardines on wholemeal toast with lemon. Ultra omega-3 recovery food.', photo_keyword: 'sardine-toast' },
  { name: 'Ginger and Carrot Soup', calories: 190, goal: 'recovery', emoji: '🥕', description: 'Roasted carrots with fresh ginger and turmeric. Soothing anti-inflammatory soup.', photo_keyword: 'ginger-carrot-soup' },
  { name: 'Walnut and Berry Porridge', calories: 350, goal: 'recovery', emoji: '🫐', description: 'Steel-cut oats with walnuts, berries and maple syrup. Recovery breakfast powerhouse.', photo_keyword: 'berry-porridge' },
  { name: 'Tart Cherry Juice and Granola', calories: 280, goal: 'recovery', emoji: '🍒', description: 'Tart cherry juice with Greek yoghurt and granola. Classic recovery combination.', photo_keyword: 'granola-cherries' },
  { name: 'Baked Salmon with Asparagus', calories: 410, goal: 'recovery', emoji: '🦐', description: 'Baked salmon fillet with roasted asparagus and olive oil. Anti-inflammatory nutrients.', photo_keyword: 'baked-salmon-asparagus' },
  { name: 'Spinach and Chickpea Curry', calories: 380, goal: 'recovery', emoji: '🥘', description: 'Spiced chickpeas with iron-rich spinach. Turmeric-based recovery meal.', photo_keyword: 'chickpea-curry-spinach' },
  { name: 'Pineapple and Cottage Cheese', calories: 240, goal: 'recovery', emoji: '🍍', description: 'Fresh pineapple (bromelain) with cottage cheese. Recovery enzyme boost.', photo_keyword: 'pineapple-cottage-cheese' },
  { name: 'Anti-Inflammatory Smoothie Bowl', calories: 320, goal: 'recovery', emoji: '🥣', description: 'Berries, turmeric, ginger and protein. Topped with granola and coconut.', photo_keyword: 'smoothie-bowl-berries' },
  { name: 'Brown Rice and Edamame', calories: 360, goal: 'recovery', emoji: '🍚', description: 'Brown rice with edamame and stir-fried vegetables. Complete recovery carbs.', photo_keyword: 'brown-rice-edamame' },
  { name: 'Beetroot and Walnut Salad', calories: 280, goal: 'recovery', emoji: '🥗', description: 'Roasted beetroot with walnuts and feta. Nitrates for recovery circulation.', photo_keyword: 'beetroot-walnut-salad' },
  { name: 'Coconut and Mango Chia Bowl', calories: 310, goal: 'recovery', emoji: '🥭', description: 'Mango, coconut milk, chia seeds and granola. Tropical recovery bowl.', photo_keyword: 'mango-chia-bowl' },
  { name: 'Turkey and Vegetable Stew', calories: 390, goal: 'recovery', emoji: '🍲', description: 'Lean turkey with carrots, celery and herbs. Warming recovery stew.', photo_keyword: 'turkey-vegetable-stew' },
  { name: 'Pumpkin Seed and Kale Salad', calories: 270, goal: 'recovery', emoji: '🥗', description: 'Massaged kale with pumpkin seeds and tahini dressing. Nutrient-dense recovery meal.', photo_keyword: 'kale-salad-seeds' },
  { name: 'Lemon Ginger Green Tea Smoothie', calories: 160, goal: 'recovery', emoji: '🍃', description: 'Green tea, lemon, ginger and honey. Antioxidant recovery drink.', photo_keyword: 'green-tea-smoothie' },
  { name: 'Overnight Oats with Cherries', calories: 340, goal: 'recovery', emoji: '🍒', description: 'Overnight oats with tart cherry juice and almonds. Recovery sleep meal.', photo_keyword: 'overnight-oats-cherries' },
  { name: 'Mackerel and Sweet Potato', calories: 430, goal: 'recovery', emoji: '🐟', description: 'Oily mackerel with roasted sweet potato. Omega-3 and carb recovery meal.', photo_keyword: 'mackerel-sweet-potato' },
  { name: 'Collagen Protein Shake', calories: 200, goal: 'recovery', emoji: '🥤', description: 'Collagen powder, banana and almond milk. Joint recovery protein drink.', photo_keyword: 'protein-shake' },
  { name: 'Warm Lemon and Honey Water with Toast', calories: 180, goal: 'recovery', emoji: '🍯', description: 'Warm lemon water with honey and wholemeal toast. Soothing recovery drink.', photo_keyword: 'honey-lemon-toast' },

  // PRE-WORKOUT - 25 meals
  { name: 'Banana and Peanut Butter', calories: 290, goal: 'pre-workout', emoji: '🍌', description: 'Ripe banana with 2 tbsp peanut butter. Perfect pre-workout fast carbs.', photo_keyword: 'banana-peanut-butter' },
  { name: 'Oat and Honey Energy Balls', calories: 240, goal: 'pre-workout', emoji: '⚪', description: 'Homemade oats, honey and nuts. Portable pre-workout energy boost.', photo_keyword: 'energy-balls-oats' },
  { name: 'Rice Cakes with Almond Butter', calories: 220, goal: 'pre-workout', emoji: '🍚', description: 'Plain rice cakes with almond butter. Simple fast carbs with healthy fat.', photo_keyword: 'rice-cakes-almond' },
  { name: 'Fruit and Granola Yoghurt', calories: 310, goal: 'pre-workout', emoji: '🥛', description: 'Greek yoghurt with granola, banana and berries. Pre-workout energy bowl.', photo_keyword: 'granola-yoghurt-fruit' },
  { name: 'Dates and Almonds', calories: 200, goal: 'pre-workout', emoji: '📅', description: 'Medjool dates with raw almonds. Natural sugars for training energy.', photo_keyword: 'dates-almonds' },
  { name: 'Wholegrain Toast with Jam', calories: 180, goal: 'pre-workout', emoji: '🍞', description: 'Wholemeal toast with fruit jam. Quick-digesting carbs pre-training.', photo_keyword: 'wholegrain-toast-jam' },
  { name: 'Banana and Oat Smoothie', calories: 270, goal: 'pre-workout', emoji: '🥤', description: 'Banana, oats and milk blended smooth. Liquid pre-workout meal.', photo_keyword: 'banana-oat-smoothie' },
  { name: 'Apple and Peanut Butter', calories: 250, goal: 'pre-workout', emoji: '🍎', description: 'Sliced apple with peanut butter dip. Carbs with sustained energy.', photo_keyword: 'apple-peanut-butter' },
  { name: 'Orange and Almond Snack', calories: 190, goal: 'pre-workout', emoji: '🍊', description: 'Fresh orange with handful of almonds. Vitamin C and healthy fats.', photo_keyword: 'orange-almonds' },
  { name: 'Mango and Lime Smoothie', calories: 220, goal: 'pre-workout', emoji: '🥭', description: 'Fresh mango, lime juice and coconut water. Tropical pre-workout drink.', photo_keyword: 'mango-lime-smoothie' },
  { name: 'Wholegrain Bagel with Honey', calories: 300, goal: 'pre-workout', emoji: '🥯', description: 'Toasted bagel with honey drizzle. Dense carbs for intense training.', photo_keyword: 'bagel-honey' },
  { name: 'Carrot and Hummus', calories: 170, goal: 'pre-workout', emoji: '🥕', description: 'Fresh carrot sticks with hummus dip. Natural carbs and healthy fats.', photo_keyword: 'carrot-hummus' },
  { name: 'Porridge with Maple Syrup', calories: 320, goal: 'pre-workout', emoji: '🥣', description: 'Warm oatmeal with maple syrup and banana. Classic training fuel.', photo_keyword: 'porridge-maple' },
  { name: 'Watermelon Juice', calories: 120, goal: 'pre-workout', emoji: '🍉', description: 'Fresh watermelon juice. Hydration and natural sugars pre-workout.', photo_keyword: 'watermelon-juice' },
  { name: 'Pineapple and Coconut Smoothie', calories: 240, goal: 'pre-workout', emoji: '🍍', description: 'Pineapple, coconut milk and honey. Tropical carb-loading drink.', photo_keyword: 'pineapple-coconut-smoothie' },
  { name: 'Sweet Potato Toast', calories: 210, goal: 'pre-workout', emoji: '🥔', description: 'Toasted sweet potato slices with almond butter. Complex carbs pre-training.', photo_keyword: 'sweet-potato-toast' },
  { name: 'Dried Fruit and Nut Mix', calories: 280, goal: 'pre-workout', emoji: '🥜', description: 'Mixed dried fruits and nuts. Portable pre-workout energy mix.', photo_keyword: 'dried-fruit-nuts' },
  { name: 'Chocolate Milk', calories: 200, goal: 'pre-workout', emoji: '🥛', description: 'Low-fat chocolate milk. Simple carbs and quick energy pre-training.', photo_keyword: 'chocolate-milk' },
  { name: 'Whole Wheat Pasta with Olive Oil', calories: 380, goal: 'pre-workout', emoji: '🍝', description: 'Plain whole wheat pasta with olive oil. Pre-workout carb loading meal.', photo_keyword: 'pasta-olive-oil' },
  { name: 'Melon and Prosciutto', calories: 220, goal: 'pre-workout', emoji: '🍈', description: 'Fresh melon wrapped with prosciutto. Light pre-workout with carbs and salt.', photo_keyword: 'melon-prosciutto' },
  { name: 'Coconut Water and Banana', calories: 180, goal: 'pre-workout', emoji: '🥥', description: 'Coconut water with ripe banana. Electrolytes and carbs for hydration.', photo_keyword: 'coconut-water-banana' },
  { name: 'Peanut Butter Smoothie', calories: 310, goal: 'pre-workout', emoji: '🥤', description: 'Peanut butter, banana and oat milk. Pre-workout protein-carb drink.', photo_keyword: 'peanut-butter-smoothie' },
  { name: 'Raisin and Oat Cookie', calories: 230, goal: 'pre-workout', emoji: '🍪', description: 'Homemade oat cookie with raisins. Quick energy pre-training snack.', photo_keyword: 'oat-raisin-cookie' },
  { name: 'Beet and Berry Smoothie', calories: 200, goal: 'pre-workout', emoji: '🫐', description: 'Beet, berry and banana smoothie. Nitrates for pre-workout circulation.', photo_keyword: 'beet-berry-smoothie' },
  { name: 'Toast with Avocado and Honey', calories: 290, goal: 'pre-workout', emoji: '🍞', description: 'Wholemeal toast with avocado and honey drizzle. Carbs and healthy fats.', photo_keyword: 'avocado-honey-toast' },
];

module.exports = MEALS_DATA;
