// backend/src/db/seedNutrition.js
const { getDb } = require('./database');

const TIPS = [
  // Pre-workout
  { category: 'pre-workout', title: 'Eat 90 Minutes Before Training', content: 'Have a balanced meal 90 minutes before your workout. Include complex carbs like oats or sweet potato for sustained energy, plus a lean protein source to protect muscle tissue during exercise.' },
  { category: 'pre-workout', title: 'Banana Before Cardio', content: 'A banana 30 minutes before cardio gives you a quick hit of natural sugars and potassium. This helps prevent muscle cramps and provides fast-acting energy without weighing you down.' },
  { category: 'pre-workout', title: 'Stay Hydrated Before You Start', content: 'Drink 500ml of water 2 hours before exercise. Even mild dehydration of 2% body weight can reduce performance by up to 10%. Starting hydrated means better focus, endurance and strength.' },
  { category: 'pre-workout', title: 'Caffeine for Performance', content: 'A cup of black coffee 45–60 minutes before training can boost performance by 10–15%. Caffeine increases adrenaline, improves focus and helps you push harder for longer. Avoid adding sugar.' },
  { category: 'pre-workout', title: 'Carbs Are Your Friend', content: 'Do not fear carbohydrates before a workout. Glycogen stored from carbs is your muscles primary fuel source. Rice cakes with peanut butter or a small bowl of porridge are excellent pre-workout choices.' },
  { category: 'pre-workout', title: 'Avoid High Fat Before Training', content: 'High fat meals slow digestion and can leave you feeling sluggish during training. Save fatty foods for after your session when your body is in recovery mode and can put them to better use.' },
  { category: 'pre-workout', title: 'Rice Cakes with Peanut Butter', content: 'Two rice cakes with a tablespoon of peanut butter gives you the perfect pre-workout balance: fast carbs from the rice cakes and slow-release energy from the healthy fats in peanut butter.' },
  { category: 'pre-workout', title: 'Time Your Protein Right', content: 'Include 20–30g of protein in your pre-workout meal to start muscle protein synthesis. Greek yogurt, chicken or a protein shake are ideal. This primes your muscles for growth during training.' },
  // Hydration
  { category: 'hydration', title: 'Drink Water First Thing', content: 'After 7–8 hours of sleep your body is dehydrated. Drink 500ml of water immediately upon waking to kickstart your metabolism, flush out toxins and improve mental clarity before the day begins.' },
  { category: 'hydration', title: 'Add Electrolytes After Sweating', content: 'If you have sweated heavily during training, plain water alone is not enough. Add a pinch of sea salt and squeeze of lemon to your water, or use an electrolyte tablet to replenish sodium, potassium and magnesium.' },
  { category: 'hydration', title: '2 Litres Minimum Per Day', content: 'Aim for at least 2 litres of water daily, more if you exercise or live in a warm climate. Proper hydration improves nutrient delivery, joint lubrication, skin health and mental performance.' },
  { category: 'hydration', title: 'Green Tea for Metabolism', content: 'Green tea contains EGCG, a compound that boosts fat oxidation by up to 17%. Drink 2–3 cups daily for antioxidant benefits, gentle caffeine and metabolic support without the jitters of coffee.' },
  { category: 'hydration', title: 'Check Your Urine Colour', content: 'Pale yellow urine means you are well hydrated. Dark yellow means drink more water now. Clear urine can mean over-hydration. This simple daily check is the easiest hydration monitor you have.' },
  { category: 'hydration', title: 'Coconut Water Post Workout', content: 'Coconut water is natures sports drink. It contains natural electrolytes including potassium, magnesium and sodium. After a tough session it rehydrates faster than plain water without artificial additives.' },
  { category: 'hydration', title: 'Herbal Teas Count', content: 'Herbal teas like chamomile, peppermint and ginger contribute to your daily fluid intake. They also provide anti-inflammatory compounds and can aid sleep, digestion and stress reduction.' },
  { category: 'hydration', title: 'Limit Alcohol on Training Days', content: 'Alcohol is a diuretic that dehydrates you and impairs muscle protein synthesis for up to 24 hours after consumption. On training days, alcohol significantly reduces the gains from your workout.' },
  // Recovery
  { category: 'recovery', title: 'Eat Protein Within 30 Minutes', content: 'The anabolic window after training is real. Consuming 25–40g of protein within 30 minutes of finishing your workout maximises muscle repair and growth. A whey protein shake is the fastest option.' },
  { category: 'recovery', title: 'Tart Cherry Juice for Soreness', content: 'Tart cherry juice is one of the most researched recovery foods. It contains anthocyanins that reduce inflammation and muscle damage. Drink 250ml twice daily on heavy training days to reduce DOMS.' },
  { category: 'recovery', title: 'Sleep Is the Best Recovery Tool', content: 'During deep sleep your body releases growth hormone and repairs damaged muscle tissue. Aim for 7–9 hours. Eating a slow-digesting protein like cottage cheese or casein before bed supports overnight recovery.' },
  { category: 'recovery', title: 'Omega 3 Reduces Inflammation', content: 'Omega 3 fatty acids found in salmon, mackerel, sardines and walnuts reduce exercise-induced inflammation. Taking 2–3g of fish oil daily or eating oily fish three times a week improves recovery and joint health.' },
  { category: 'recovery', title: 'Carb Up After Hard Sessions', content: 'After intense training your glycogen stores are depleted. Eating 1–1.5g of carbohydrates per kilogram of body weight within 2 hours post-workout speeds recovery and prepares you for tomorrow s session.' },
  { category: 'recovery', title: 'Turmeric and Black Pepper', content: 'Curcumin in turmeric is a powerful anti-inflammatory. Adding black pepper increases absorption by 2000%. Add turmeric and black pepper to your meals or take a curcumin supplement to reduce muscle soreness.' },
  { category: 'recovery', title: 'Magnesium for Muscle Relaxation', content: 'Magnesium is essential for muscle relaxation, sleep quality and protein synthesis. Many athletes are deficient. Eat pumpkin seeds, dark chocolate, spinach and almonds or supplement with 300–400mg before bed.' },
  { category: 'recovery', title: 'Cold Water Helps Short Term', content: 'Cold water immersion after training reduces acute inflammation and perceived soreness. A 10-minute cold shower or ice bath can reduce next-day muscle pain, though it may slightly blunt long-term muscle adaptation.' },
  // Weight Loss
  { category: 'weight-loss', title: 'Protein Keeps You Full', content: 'Protein has the highest satiety of all macronutrients. Eating 30g of protein at each meal reduces hunger hormones and increases fullness hormones, making it easier to maintain a calorie deficit without feeling deprived.' },
  { category: 'weight-loss', title: 'Eat Slowly and Mindfully', content: 'It takes 20 minutes for your stomach to signal fullness to your brain. Eating slowly reduces calorie intake by up to 10% without trying. Put your fork down between bites and chew each mouthful thoroughly.' },
  { category: 'weight-loss', title: 'Volume Eating Strategy', content: 'Fill half your plate with vegetables. They are low in calories but high in fibre and water, creating volume in your stomach. You will feel full on fewer calories while getting more nutrients.' },
  { category: 'weight-loss', title: 'Avoid Liquid Calories', content: 'Smoothies, juices, lattes and alcohol add hundreds of calories that do not satisfy hunger. Swap sugary drinks for water, black coffee or herbal tea. This single change can create a 300–500 calorie daily deficit.' },
  { category: 'weight-loss', title: 'Sleep More to Weigh Less', content: 'Sleep deprivation increases the hunger hormone ghrelin by 15% and decreases the fullness hormone leptin. Less than 7 hours of sleep per night makes fat loss significantly harder regardless of diet quality.' },
  { category: 'weight-loss', title: 'Cook at Home More Often', content: 'Restaurant and takeaway meals contain on average 200–500 more calories than home-cooked equivalents due to larger portions, extra oils and hidden sugars. Cooking at home gives you full control over ingredients.' },
  { category: 'weight-loss', title: 'Never Skip Breakfast', content: 'Eating a protein-rich breakfast reduces calorie intake for the rest of the day. People who skip breakfast tend to overcompensate later with higher-calorie, lower-quality food choices throughout the day.' },
  { category: 'weight-loss', title: 'Track What You Eat', content: 'Studies show that people who track their food intake lose twice as much weight as those who do not. Even tracking for just 3 days a week creates enough awareness to improve food choices significantly.' },
  { category: 'weight-loss', title: 'Intermittent Fasting Basics', content: 'A 16:8 intermittent fasting approach — eating within an 8-hour window — can reduce overall calorie intake without counting calories. It also improves insulin sensitivity and may enhance fat burning during the fasted state.' },
  { category: 'weight-loss', title: 'Spice Up Your Meals', content: 'Chilli, cayenne pepper and ginger temporarily boost metabolism by 4–5%. They also add flavour, reducing the need for calorie-dense sauces and dressings. Add chilli flakes to eggs, stir-fries and soups.' },
  // Muscle Gain
  { category: 'muscle-gain', title: 'Aim for 1.6–2.2g Protein Per KG', content: 'To build muscle you need sufficient protein. Research supports 1.6–2.2g of protein per kilogram of bodyweight daily. For an 80kg person this is 128–176g daily, spread across 4–5 meals for optimal absorption.' },
  { category: 'muscle-gain', title: 'Eat in a Calorie Surplus', content: 'Muscle growth requires extra energy. Aim for 250–500 calories above your maintenance intake for a lean bulk. Too large a surplus adds unwanted fat. Track your weight weekly and adjust accordingly.' },
  { category: 'muscle-gain', title: 'Leucine Triggers Muscle Growth', content: 'Leucine is the key amino acid that triggers muscle protein synthesis. Foods highest in leucine include whey protein, eggs, chicken, beef and tuna. Ensure every meal contains at least 2–3g of leucine.' },
  { category: 'muscle-gain', title: 'Creatine Is the Most Researched', content: 'Creatine monohydrate is the most studied sports supplement with hundreds of studies supporting its safety and effectiveness. Take 3–5g daily to increase strength, power output and muscle volume over time.' },
  { category: 'muscle-gain', title: 'Time Carbs Around Workouts', content: 'Eat the majority of your daily carbohydrates before and after training. Pre-workout carbs fuel the session. Post-workout carbs spike insulin which helps drive protein and nutrients into muscle cells for recovery.' },
  { category: 'muscle-gain', title: 'Do Not Fear Fat', content: 'Healthy fats from avocado, nuts, eggs and olive oil support testosterone production, which is essential for muscle growth. Aim for 20–30% of total calories from fat. Low fat diets can reduce anabolic hormones.' },
  { category: 'muscle-gain', title: 'Eat Every 3–4 Hours', content: 'Spreading protein intake across 4–5 meals every 3–4 hours maintains elevated muscle protein synthesis throughout the day. This is more effective than eating the same total protein in 1–2 large meals.' },
  { category: 'muscle-gain', title: 'Pre-Sleep Protein Matters', content: 'Consuming 30–40g of casein protein before bed stimulates overnight muscle protein synthesis. Cottage cheese, Greek yogurt or a casein shake are ideal. Your muscles are literally growing while you sleep.' },
  // General
  { category: 'general', title: 'Eat the Rainbow', content: 'Different coloured vegetables and fruits contain different phytonutrients and antioxidants. Aim for 5 different colours on your plate daily. Red peppers, purple cabbage, orange carrots, green spinach and yellow corn.' },
  { category: 'general', title: 'Read Food Labels', content: 'Food labels reveal the truth about what you are eating. Check serving size first, then calories, protein, sugar and saturated fat. Ingredients are listed by weight — if sugar is in the first three, put it back.' },
  { category: 'general', title: 'Meal Prep on Sundays', content: 'Spending 2 hours on Sunday preparing meals for the week removes the decision fatigue of daily cooking. Batch cook proteins, chop vegetables and prepare grains so healthy eating becomes effortless on busy weekdays.' },
  { category: 'general', title: 'Gut Health Is Everything', content: 'Your gut microbiome influences immunity, mood, energy and metabolism. Eat fermented foods daily — live yogurt, kefir, kimchi, sauerkraut or kombucha — and eat 30 different plant foods per week for diversity.' },
  { category: 'general', title: 'Reduce Ultra-Processed Foods', content: 'Ultra-processed foods are designed to override your hunger signals and make you overeat. They contain additives, preservatives and refined ingredients that cause inflammation. Cook from whole ingredients as much as possible.' },
  { category: 'general', title: 'The 80/20 Rule', content: 'Eat nutrient-dense whole foods 80% of the time and allow flexibility 20% of the time. This approach is sustainable long term. Strict perfection leads to all-or-nothing thinking, which is the enemy of consistency.' },
  { category: 'general', title: 'Zinc for Immunity and Hormones', content: 'Zinc supports immune function, testosterone production and wound healing. The best sources are oysters, red meat, pumpkin seeds and chickpeas. Many people are deficient, especially those who train intensively.' },
  { category: 'general', title: 'Vitamin D and Sunshine', content: 'Vitamin D deficiency is extremely common in the UK and affects immune function, mood, bone density and muscle performance. Get 15 minutes of midday sun when possible or supplement with 2000–4000 IU daily in winter.' },
  { category: 'general', title: 'Fibre for Everything', content: 'Aim for 25–35g of dietary fibre daily from vegetables, fruits, legumes and wholegrains. Fibre feeds beneficial gut bacteria, improves cholesterol, stabilises blood sugar and keeps you feeling full between meals.' },
  { category: 'general', title: 'Iron for Energy', content: 'Iron deficiency causes fatigue, brain fog and reduced athletic performance. Women who train heavily are especially at risk. Eat red meat, lentils and spinach regularly, and pair plant iron sources with vitamin C for better absorption.' },
  { category: 'general', title: 'Cook with Olive Oil', content: 'Extra virgin olive oil is rich in oleocanthal, a natural anti-inflammatory as powerful as ibuprofen at typical dietary doses. Use it for low-heat cooking, salad dressings and drizzling over vegetables.' },
  { category: 'general', title: 'Eggs Are a Superfood', content: 'Whole eggs contain all 9 essential amino acids, vitamins D, B12, choline and lutein for eye health. The yolk contains most of the nutrition. Unless you have specific cholesterol issues, eat whole eggs daily.' },
  { category: 'general', title: 'Plan Your Meals in Advance', content: 'People who plan their meals in advance consume 40% more vegetables and 25% fewer calories from snacks. Take 10 minutes on Sunday evening to write out what you will eat each day of the coming week.' },
  { category: 'general', title: 'Beans and Legumes Weekly', content: 'Lentils, chickpeas, black beans and kidney beans are among the most nutrient-dense foods on the planet. High in protein, fibre, iron and folate. Eating them 3 times a week improves gut health and reduces cardiovascular risk.' },
  { category: 'general', title: 'Snack Smart', content: 'Prepare healthy snacks in advance so you are never caught hungry with poor options. Greek yogurt with berries, apple with almond butter, hard boiled eggs or a small handful of mixed nuts are all excellent choices.' },
  { category: 'general', title: 'Avoid Eating While Distracted', content: 'Eating while watching TV or scrolling on your phone leads to consuming up to 25% more calories per meal. Mindful eating — focusing only on your food — improves enjoyment, digestion and helps you recognise fullness cues.' },
  { category: 'general', title: 'Wholegrains Over Refined', content: 'Swap white bread, white rice and regular pasta for wholegrain versions. Wholegrains retain the bran and germ, providing more fibre, vitamins and slower-releasing energy. This simple swap reduces hunger and improves blood sugar control.' },
  { category: 'general', title: 'Berries Every Day', content: 'Blueberries, strawberries and raspberries are among the highest antioxidant foods available. They improve cognitive function, reduce inflammation and are low in sugar. Add a handful to your morning yogurt or oats daily.' },
  { category: 'general', title: 'Dark Chocolate for Antioxidants', content: '70% or higher dark chocolate contains flavanols that improve blood flow, reduce blood pressure and enhance brain function. A 20–30g square after dinner is a healthy, satisfying treat that is good for your cardiovascular system.' },
  { category: 'general', title: 'Nuts for Heart Health', content: 'A 30g daily serving of mixed nuts reduces cardiovascular disease risk by 28%. Walnuts are particularly beneficial, containing alpha-linolenic acid, an omega 3 that reduces inflammation and supports brain health.' },
  { category: 'general', title: 'Sweet Potato Over White Potato', content: 'Sweet potatoes provide the same satisfying carbohydrates as white potatoes but with significantly more vitamin A, vitamin C, potassium and fibre. They have a lower glycaemic index, producing a gentler blood sugar response.' },
  { category: 'general', title: 'Greek Yogurt Daily', content: 'Full fat Greek yogurt provides 15–20g of protein per 200g serving, plus live cultures for gut health, calcium for bone density and casein protein for sustained amino acid release. It is one of the most versatile healthy foods.' },
  { category: 'general', title: 'Limit Added Sugar', content: 'The World Health Organisation recommends no more than 25g of added sugar daily. Most people consume 2–3 times this amount. Hidden sugars lurk in sauces, bread, flavoured yogurts and cereals. Check labels every time.' },
  { category: 'general', title: 'Garlic for Immune Function', content: 'Allicin in garlic has potent antimicrobial and immune-boosting properties. It also reduces blood pressure and improves cholesterol. Crush garlic and let it sit for 10 minutes before cooking to maximise allicin production.' },
  { category: 'general', title: 'Salmon Twice a Week', content: 'Two portions of oily fish like salmon, mackerel or sardines per week provides sufficient omega 3 for most people. Wild-caught salmon is highest in EPA and DHA, the omega 3 fatty acids most beneficial for inflammation and brain health.' },
  { category: 'general', title: 'Cook Broccoli Correctly', content: 'Sulforaphane, the anti-cancer compound in broccoli, is activated when the cell walls are damaged. Chop broccoli and leave it for 40 minutes before cooking, or eat it raw to maximise sulforaphane content.' },
  { category: 'general', title: 'Apple Cider Vinegar Before Meals', content: 'One tablespoon of apple cider vinegar in water before meals improves insulin sensitivity, reduces blood sugar spikes after eating and may increase feelings of fullness. It also supports digestive acid production.' },
  { category: 'general', title: 'Eat More Avocado', content: 'Avocados are rich in monounsaturated fats, potassium, folate and vitamins K, C, B5 and B6. They increase absorption of fat-soluble nutrients from other vegetables by up to 400% when eaten together.' },
  { category: 'general', title: 'Oats for Cholesterol', content: 'Beta-glucan fibre in oats actively reduces LDL cholesterol. Eating 70g of oats daily can lower bad cholesterol by 5–7% in 4–6 weeks. Oats also provide slow-releasing energy, iron and B vitamins.' },
  { category: 'general', title: 'Spinach in Everything', content: 'Spinach is one of the most nutrient-dense foods per calorie. It is rich in iron, calcium, vitamin K, folate and lutein. Add a large handful to smoothies, scrambled eggs, pasta and soups without affecting the taste significantly.' },
  { category: 'general', title: 'Hydrate Before Each Meal', content: 'Drinking a large glass of water 20–30 minutes before each meal naturally reduces portion size and calorie intake. It also ensures you are not confusing thirst for hunger, which is an extremely common occurrence.' },
  { category: 'general', title: 'Fermented Foods Daily', content: 'Kefir, live yogurt, kimchi, sauerkraut, miso and kombucha contain billions of beneficial bacteria that colonise your gut. A diverse gut microbiome is associated with better immunity, lower inflammation and improved mental health.' },
  { category: 'general', title: 'Protein at Every Meal', content: 'Include a protein source at every meal and snack. Protein requires more energy to digest than carbs or fat, keeps you full longer and provides the building blocks for muscle, hormones, enzymes and immune cells.' },
  { category: 'general', title: 'Cooking Methods Matter', content: 'Boiling destroys water-soluble vitamins. Steaming retains up to 90% more nutrients. Roasting concentrates flavour without adding calories. Frying adds significant fat. For most vegetables, steam or roast for best nutrition.' },
  { category: 'general', title: 'Eat Seasonal and Local', content: 'Seasonal produce is harvested at peak ripeness and contains significantly more nutrients than out-of-season produce picked early and transported long distances. Visit a local farmers market when possible for maximum nutritional quality.' },
  { category: 'general', title: 'Dont Fear Carbohydrates', content: 'Carbohydrates are not the enemy. The quality and quantity of carbohydrates matters. Choose wholegrains, vegetables, fruits and legumes over refined carbs. These provide fibre, vitamins and sustained energy for active people.' },
  { category: 'general', title: 'Portion Control Without Weighing', content: 'Use your hand as a portion guide. A palm of protein, a fist of vegetables, a cupped hand of carbs and a thumb of healthy fats per meal is a simple system that works well without needing a food scale.' },
  { category: 'general', title: 'Chew Your Food Properly', content: 'Chewing breaks food into smaller pieces and mixes it with saliva containing digestive enzymes. Proper chewing improves nutrient absorption, reduces bloating and gives your brain time to register fullness signals.' },
  { category: 'general', title: 'Include Colour at Every Meal', content: 'A colourful plate ensures nutritional diversity. Each colour in plants represents different antioxidants and phytonutrients. Red lycopene, orange beta-carotene, purple anthocyanins and green chlorophyll all play unique health roles.' },
  { category: 'general', title: 'Reduce Sodium Intake', content: 'Most people consume double the recommended daily sodium limit. High sodium causes water retention, raises blood pressure and strains the cardiovascular system. Cook at home and season with herbs and spices instead of salt.' },
  { category: 'general', title: 'Batch Cook Legumes', content: 'Dried lentils, chickpeas and black beans are cheap, nutritious and incredibly versatile. Cook a large batch weekly and add them to salads, stews, curries and soups. They provide protein and fibre for pennies per serving.' },
  { category: 'general', title: 'Breakfast Should Be Protein Rich', content: 'Starting the day with 25–30g of protein stabilises blood sugar, reduces cravings throughout the day and supports muscle maintenance. Eggs, Greek yogurt, smoked salmon or a protein shake are excellent breakfast proteins.' },
  { category: 'general', title: 'Know Your Portion of Nuts', content: 'Nuts are incredibly nutritious but calorie-dense at 600–700 calories per 100g. A healthy daily serving is 30g — roughly a small closed handful. Eating straight from the bag makes overconsumption very easy.' },
  { category: 'general', title: 'Dont Drink Your Calories', content: 'Liquid calories are poorly registered by the brain compared to solid food calories. A 500ml smoothie with 400 calories does not satisfy hunger the same way as a 400 calorie meal. Choose whole foods over blended versions.' },
  { category: 'general', title: 'Iodine for Thyroid Health', content: 'Iodine is essential for thyroid hormone production which regulates metabolism. Many people in the UK are mildly deficient. Eat seaweed, fish, dairy and iodised salt. Thyroid dysfunction can cause fatigue and weight gain.' },
  { category: 'general', title: 'Use Smaller Plates', content: 'Research shows that switching from a 30cm to a 25cm plate reduces food intake by 22% without any conscious effort or feelings of deprivation. Your brain judges portion size relative to the container it is served in.' },
  { category: 'general', title: 'Eat Protein Before Carbs', content: 'Eating protein and vegetables before carbohydrates at the same meal reduces the blood sugar spike from that meal by up to 37%. This simple change can improve energy levels, reduce afternoon crashes and support fat loss.' },
  { category: 'general', title: 'Liver Is the Original Superfood', content: 'Chicken liver is one of the most nutrient-dense foods on earth. It provides more vitamin A, B12, folate, iron, copper and zinc per gram than almost any other food. Eat it once a week for extraordinary nutritional density.' },
  { category: 'general', title: 'The Power of Bone Broth', content: 'Bone broth is rich in collagen, glycine, glucosamine and minerals. Drinking a cup daily supports gut lining integrity, joint health, skin elasticity and quality sleep. Make it yourself or buy quality pre-made versions.' },
  { category: 'general', title: 'Brassicas Three Times Weekly', content: 'Broccoli, cauliflower, Brussels sprouts, kale and cabbage contain glucosinolates that support liver detoxification and reduce cancer risk. Eating cruciferous vegetables three or more times per week has significant health benefits.' },
  { category: 'general', title: 'B Vitamins for Energy', content: 'B vitamins are essential cofactors in energy metabolism. Deficiency causes fatigue, brain fog and irritability. The best sources are meat, eggs, dairy, legumes and wholegrains. Vegans should supplement B12 without exception.' },
];

const MEALS = [
  { name: 'High Protein Scrambled Eggs', calories: 420, goal: 'muscle-gain', emoji: '🍳', description: 'Fluffy scrambled eggs with smoked salmon, spinach and avocado. High protein, healthy fats and nutrient-dense greens in one quick pan.', ingredients: JSON.stringify(['4 large eggs', '100g smoked salmon', 'Large handful spinach', '½ avocado', '1 tsp butter', 'Salt and pepper', 'Fresh dill (optional)']), method: JSON.stringify(['Crack eggs into a bowl, season with salt and pepper and whisk well.', 'Melt butter in a non-stick pan over low heat.', 'Add eggs and stir gently and continuously with a spatula.', 'When almost set, remove from heat and fold in spinach and smoked salmon.', 'Serve topped with sliced avocado and fresh dill.']), protein: 45, carbs: 8, fat: 28, photo_url: 'https://images.unsplash.com/photo-1482049016688-2d3e1b311543?w=800&q=80' },
  { name: 'Chicken and Sweet Potato Bowl', calories: 520, goal: 'muscle-gain', emoji: '🍗', description: 'Grilled chicken breast with roasted sweet potato, broccoli and a tahini drizzle. A complete high-protein muscle building meal.', ingredients: JSON.stringify(['200g chicken breast', '1 medium sweet potato', '150g broccoli', '2 tbsp tahini', '1 lemon', '1 tsp paprika', 'Olive oil', 'Salt and pepper']), method: JSON.stringify(['Preheat oven to 200°C. Cube sweet potato and toss with olive oil, paprika and salt.', 'Roast sweet potato for 25 minutes until tender.', 'Season chicken with paprika, salt and pepper. Grill for 6–7 minutes each side.', 'Steam broccoli for 4 minutes until bright green and tender.', 'Mix tahini with lemon juice and water to make a drizzle.', 'Assemble bowl and drizzle with tahini sauce.']), protein: 52, carbs: 45, fat: 14, photo_url: 'https://images.unsplash.com/photo-1546793665-c74683f339c1?w=800&q=80' },
  { name: 'Overnight Oats with Berries', calories: 380, goal: 'pre-workout', emoji: '🫐', description: 'Creamy overnight oats packed with protein and antioxidants. Prepare the night before for the perfect pre-training breakfast.', ingredients: JSON.stringify(['80g rolled oats', '200ml oat milk', '150g Greek yogurt', '1 scoop vanilla protein powder', '100g mixed berries', '1 tbsp chia seeds', '1 tsp honey', 'Pinch of cinnamon']), method: JSON.stringify(['Combine oats, oat milk, Greek yogurt and protein powder in a jar.', 'Stir in chia seeds, honey and cinnamon.', 'Seal and refrigerate overnight or for at least 6 hours.', 'In the morning, top with fresh berries and an extra drizzle of honey.']), protein: 32, carbs: 48, fat: 8, photo_url: 'https://images.unsplash.com/photo-1517673400267-0251440c45dc?w=800&q=80' },
  { name: 'Salmon and Quinoa Power Bowl', calories: 560, goal: 'recovery', emoji: '🐟', description: 'Omega-3 rich salmon with protein-packed quinoa and roasted vegetables. The ultimate anti-inflammatory recovery meal.', ingredients: JSON.stringify(['180g salmon fillet', '80g quinoa', '100g cherry tomatoes', '1 cucumber', '½ red onion', '2 tbsp olive oil', '1 lemon', '50g rocket leaves', '2 tbsp pumpkin seeds']), method: JSON.stringify(['Cook quinoa according to package instructions.', 'Season salmon with lemon zest, salt and pepper. Pan fry in olive oil for 4 minutes each side.', 'Dice cucumber and red onion, halve tomatoes.', 'Assemble bowl with quinoa, rocket, vegetables and salmon.', 'Drizzle with lemon juice and olive oil, scatter pumpkin seeds over the top.']), protein: 48, carbs: 38, fat: 22, photo_url: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800&q=80' },
  { name: 'Turkey and Vegetable Stir Fry', calories: 440, goal: 'weight-loss', emoji: '🥦', description: 'Lean turkey mince with colourful vegetables in a ginger soy sauce. Low calorie, high protein and ready in under 20 minutes.', ingredients: JSON.stringify(['300g turkey mince', '1 red pepper', '1 yellow pepper', '150g broccoli', '150g snap peas', '3 cloves garlic', '2cm ginger', '2 tbsp low sodium soy sauce', '1 tsp sesame oil', '1 tsp cornstarch']), method: JSON.stringify(['Mix soy sauce, sesame oil and cornstarch together.', 'Heat a wok over high heat with a splash of oil.', 'Add turkey mince and cook until browned, breaking up with a spoon.', 'Add garlic and ginger, cook for 1 minute.', 'Add all vegetables and stir fry for 3–4 minutes until just tender.', 'Pour sauce over and toss to coat. Serve immediately.']), protein: 42, carbs: 22, fat: 12, photo_url: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=800&q=80' },
  { name: 'Greek Yogurt Parfait', calories: 320, goal: 'general', emoji: '🍓', description: 'Layered Greek yogurt with granola, honey and fresh fruit. High protein, probiotic-rich and ready in 3 minutes.', ingredients: JSON.stringify(['200g full fat Greek yogurt', '40g granola', '100g strawberries', '50g blueberries', '1 tbsp honey', '1 tbsp flaxseed', 'Fresh mint']), method: JSON.stringify(['Slice strawberries and wash blueberries.', 'Layer Greek yogurt in a glass or bowl.', 'Add granola, then berries, then another layer of yogurt.', 'Drizzle with honey and scatter flaxseed over the top.', 'Garnish with fresh mint and serve immediately.']), protein: 22, carbs: 42, fat: 8, photo_url: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800&q=80' },
  { name: 'Black Bean and Avocado Tacos', calories: 480, goal: 'general', emoji: '🌮', description: 'Crispy corn tacos with seasoned black beans, fresh avocado and zingy lime slaw. A plant-based high-fibre meal.', ingredients: JSON.stringify(['6 corn tortillas', '400g canned black beans', '2 avocados', '¼ red cabbage', '1 lime', '2 tsp cumin', '1 tsp smoked paprika', 'Fresh coriander', '1 red chilli', 'Salt']), method: JSON.stringify(['Shred red cabbage and toss with lime juice and salt to make quick slaw.', 'Drain and rinse black beans. Heat in a pan with cumin, paprika and salt.', 'Warm tortillas in a dry pan for 30 seconds each side.', 'Mash avocados with lime juice and salt.', 'Assemble tacos with guacamole, beans, slaw, fresh coriander and sliced chilli.']), protein: 18, carbs: 62, fat: 22, photo_url: 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=800&q=80' },
  { name: 'Tuna Nicoise Salad', calories: 390, goal: 'weight-loss', emoji: '🥗', description: 'Classic French salad with tuna, green beans, eggs and olives. Protein-packed and incredibly satisfying for a light meal.', ingredients: JSON.stringify(['200g canned tuna in spring water', '4 eggs', '200g green beans', '200g cherry tomatoes', '50g black olives', '2 tbsp capers', 'Mixed leaves', '3 tbsp olive oil', '1 tbsp red wine vinegar', 'Dijon mustard']), method: JSON.stringify(['Hard boil eggs for 8 minutes, cool and halve.', 'Blanch green beans in boiling water for 3 minutes, refresh in cold water.', 'Make dressing with olive oil, vinegar and a teaspoon of Dijon mustard.', 'Arrange leaves, tomatoes, green beans and olives on a large plate.', 'Top with tuna and eggs. Drizzle dressing over the salad.']), protein: 38, carbs: 18, fat: 18, photo_url: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&q=80' },
  { name: 'Lentil and Vegetable Curry', calories: 420, goal: 'general', emoji: '🍛', description: 'Warming red lentil dahl with coconut milk and spinach. High in plant protein, fibre and anti-inflammatory spices.', ingredients: JSON.stringify(['200g red lentils', '400ml coconut milk', '400g canned tomatoes', '200g spinach', '1 large onion', '4 cloves garlic', '2cm ginger', '2 tsp cumin', '2 tsp turmeric', '1 tsp garam masala', 'Olive oil']), method: JSON.stringify(['Soften onion in olive oil for 8 minutes.', 'Add garlic, ginger and spices, cook for 2 minutes.', 'Add lentils, tomatoes and coconut milk. Season with salt.', 'Simmer for 25 minutes until lentils are completely soft.', 'Stir in spinach until wilted. Serve with brown rice or naan.']), protein: 22, carbs: 52, fat: 14, photo_url: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800&q=80' },
  { name: 'Beef and Broccoli Rice Bowl', calories: 580, goal: 'muscle-gain', emoji: '🥩', description: 'Tender sirloin strips with broccoli in a sticky ginger sauce over brown rice. High protein post-workout recovery meal.', ingredients: JSON.stringify(['250g sirloin steak', '200g broccoli', '150g brown rice', '3 tbsp soy sauce', '1 tbsp oyster sauce', '1 tsp sesame oil', '2 cloves garlic', '1cm ginger', '1 tsp cornstarch', 'Spring onions']), method: JSON.stringify(['Cook brown rice according to instructions.', 'Slice steak thinly against the grain.', 'Mix soy sauce, oyster sauce, sesame oil and cornstarch.', 'Stir fry steak in a hot pan for 2 minutes, remove.', 'Stir fry broccoli with garlic and ginger for 3 minutes.', 'Return steak, add sauce and toss together.', 'Serve over rice with sliced spring onions.']), protein: 55, carbs: 52, fat: 16, photo_url: 'https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=800&q=80' },
  { name: 'Avocado and Egg Toast', calories: 380, goal: 'general', emoji: '🥑', description: 'Sourdough toast with smashed avocado, poached egg and everything bagel seasoning. A nutritious brunch staple.', ingredients: JSON.stringify(['2 slices sourdough bread', '1 large ripe avocado', '2 eggs', '1 lemon', 'Red chilli flakes', 'Everything bagel seasoning', 'Salt and pepper', 'Olive oil']), method: JSON.stringify(['Toast sourdough until golden and crispy.', 'Bring a pan of water to a gentle simmer. Add a splash of vinegar.', 'Create a whirlpool and drop eggs in. Poach for 3 minutes.', 'Smash avocado with lemon juice, salt and pepper.', 'Spread avocado on toast, top with poached egg.', 'Finish with chilli flakes, everything bagel seasoning and a drizzle of olive oil.']), protein: 22, carbs: 38, fat: 22, photo_url: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=800&q=80' },
  { name: 'Protein Smoothie Bowl', calories: 440, goal: 'pre-workout', emoji: '🍌', description: 'Thick blended banana, berry and protein smoothie topped with granola, seeds and fresh fruit. Delicious and energising.', ingredients: JSON.stringify(['2 frozen bananas', '150g frozen mixed berries', '1 scoop protein powder', '100ml almond milk', '2 tbsp almond butter', 'Granola for topping', 'Fresh strawberries', 'Chia seeds', 'Coconut flakes']), method: JSON.stringify(['Blend frozen bananas, berries, protein powder, almond milk and almond butter until thick and smooth.', 'Pour into a bowl — it should be thicker than a drinkable smoothie.', 'Top with granola, fresh strawberries, chia seeds and coconut flakes.', 'Eat immediately before it melts.']), protein: 34, carbs: 58, fat: 12, photo_url: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800&q=80' },
  { name: 'Chicken Caesar Salad', calories: 450, goal: 'weight-loss', emoji: '🥗', description: 'Grilled chicken over crisp romaine with homemade Caesar dressing, Parmesan and wholegrain croutons. A classic done right.', ingredients: JSON.stringify(['200g chicken breast', '2 romaine lettuce hearts', '30g Parmesan', '2 slices wholegrain bread', 'Olive oil', '2 tbsp Greek yogurt', '1 tbsp Dijon mustard', '1 clove garlic', '1 lemon', 'Worcestershire sauce']), method: JSON.stringify(['Cube bread, toss with olive oil and bake at 180°C for 10 minutes until golden.', 'Grill chicken seasoned with salt and pepper for 7 minutes each side.', 'Make dressing: blend Greek yogurt, mustard, garlic, lemon juice and a dash of Worcestershire.', 'Tear romaine into pieces, toss with dressing.', 'Top with sliced chicken, croutons and shaved Parmesan.']), protein: 48, carbs: 28, fat: 16, photo_url: 'https://images.unsplash.com/photo-1512852939750-1305098529bf?w=800&q=80' },
  { name: 'Baked Cod with Mediterranean Vegetables', calories: 380, goal: 'weight-loss', emoji: '🐠', description: 'Flaky white cod fillet on a bed of roasted courgette, pepper and tomato. Light, clean and packed with protein.', ingredients: JSON.stringify(['2 cod fillets (180g each)', '1 courgette', '2 red peppers', '200g cherry tomatoes', '1 red onion', '3 cloves garlic', '2 tbsp olive oil', 'Fresh thyme', 'Lemon zest', 'Salt and pepper']), method: JSON.stringify(['Preheat oven to 200°C.', 'Chop all vegetables and toss with olive oil, thyme and seasoning.', 'Roast vegetables for 15 minutes.', 'Season cod with lemon zest, salt and pepper.', 'Place cod on top of vegetables and bake for a further 12–15 minutes until flaky.', 'Serve with a wedge of lemon.']), protein: 42, carbs: 22, fat: 12, photo_url: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=800&q=80' },
  { name: 'Chickpea and Spinach Stew', calories: 360, goal: 'general', emoji: '🫘', description: 'Hearty Spanish-style chickpea and spinach stew with smoked paprika and tomatoes. Plant-based comfort food.', ingredients: JSON.stringify(['2 x 400g canned chickpeas', '400g canned tomatoes', '300g spinach', '1 large onion', '4 cloves garlic', '2 tsp smoked paprika', '1 tsp cumin', 'Olive oil', 'Salt', 'Crusty bread to serve']), method: JSON.stringify(['Soften onion in olive oil for 8 minutes.', 'Add garlic, paprika and cumin, cook for 2 minutes.', 'Add tomatoes and chickpeas, simmer for 15 minutes.', 'Stir in spinach until wilted.', 'Season well and serve with crusty bread for dipping.']), protein: 18, carbs: 48, fat: 10, photo_url: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=800&q=80' },
  { name: 'Egg White Omelette with Vegetables', calories: 280, goal: 'weight-loss', emoji: '🍳', description: 'Light and fluffy egg white omelette stuffed with mushrooms, peppers and goats cheese. Low calorie, high protein.', ingredients: JSON.stringify(['6 egg whites', '100g mushrooms', '½ red pepper', '30g goats cheese', 'Handful baby spinach', '1 tsp olive oil', 'Fresh chives', 'Salt and pepper']), method: JSON.stringify(['Whisk egg whites with salt and pepper until frothy.', 'Sauté mushrooms and pepper in olive oil for 4 minutes.', 'Pour egg whites over vegetables in a non-stick pan.', 'Cook over medium heat, lifting edges to let uncooked egg flow under.', 'When almost set, crumble goats cheese and add spinach.', 'Fold omelette in half and serve garnished with chives.']), protein: 30, carbs: 8, fat: 8, photo_url: 'https://images.unsplash.com/photo-1510693206972-df098062cb71?w=800&q=80' },
  { name: 'Prawn and Mango Salad', calories: 320, goal: 'weight-loss', emoji: '🦐', description: 'Juicy king prawns with fresh mango, cucumber and a zesty chilli lime dressing. Light, refreshing and exotic.', ingredients: JSON.stringify(['300g cooked king prawns', '1 ripe mango', '1 cucumber', '1 red chilli', '2 limes', '2 tbsp fish sauce', '1 tsp sugar', 'Fresh mint', 'Fresh coriander', 'Roasted peanuts']), method: JSON.stringify(['Peel and dice mango, slice cucumber into ribbons with a peeler.', 'Make dressing: mix lime juice, fish sauce and sugar until sugar dissolves.', 'Combine prawns, mango and cucumber in a bowl.', 'Pour dressing over and toss gently.', 'Top with fresh herbs, sliced chilli and crushed peanuts.']), protein: 32, carbs: 28, fat: 8, photo_url: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80' },
  { name: 'Cottage Cheese Pancakes', calories: 340, goal: 'muscle-gain', emoji: '🥞', description: 'High protein pancakes made with cottage cheese and oats. Fluffy, satisfying and macro-friendly.', ingredients: JSON.stringify(['200g cottage cheese', '2 eggs', '60g oats', '1 tsp vanilla extract', '1 tsp baking powder', 'Pinch of salt', 'Fresh berries to serve', 'Maple syrup']), method: JSON.stringify(['Blend cottage cheese, eggs, oats, vanilla and baking powder until smooth.', 'Heat a non-stick pan over medium heat with a light spray of oil.', 'Pour small ladles of batter into the pan.', 'Cook for 2–3 minutes until bubbles form, flip and cook 1–2 minutes more.', 'Serve with fresh berries and a drizzle of maple syrup.']), protein: 28, carbs: 36, fat: 8, photo_url: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=800&q=80' },
  { name: 'Vegetable and Tofu Stir Fry', calories: 380, goal: 'general', emoji: '🥢', description: 'Crispy tofu with colourful vegetables in a teriyaki glaze. A quick, plant-based protein-packed meal.', ingredients: JSON.stringify(['300g firm tofu', '1 red pepper', '1 yellow pepper', '150g broccoli', '100g snap peas', '2 carrots', '3 tbsp teriyaki sauce', '1 tsp sesame oil', '2 cloves garlic', 'Sesame seeds', 'Brown rice to serve']), method: JSON.stringify(['Press tofu between paper towels for 15 minutes, then cube.', 'Fry tofu in a hot pan with a little oil for 5 minutes each side until golden.', 'Remove tofu and stir fry all vegetables with garlic for 4 minutes.', 'Return tofu, add teriyaki sauce and sesame oil.', 'Toss together for 1 minute.', 'Serve over brown rice sprinkled with sesame seeds.']), protein: 24, carbs: 42, fat: 12, photo_url: 'https://images.unsplash.com/photo-1511690743698-d9d85f2fbf38?w=800&q=80' },
  { name: 'Grilled Chicken Burrito Bowl', calories: 540, goal: 'muscle-gain', emoji: '🌯', description: 'Mexican-inspired rice bowl with grilled chicken, black beans, corn and fresh salsa. Meal prep champion.', ingredients: JSON.stringify(['200g chicken breast', '150g brown rice', '400g black beans', 'Frozen corn', '2 avocados', '4 tomatoes', '½ red onion', '1 lime', 'Fresh coriander', 'Cumin', 'Smoked paprika']), method: JSON.stringify(['Season chicken with cumin, paprika, salt and pepper. Grill for 12–14 minutes.', 'Cook rice according to package instructions.', 'Heat black beans with a pinch of cumin and salt.', 'Make salsa with diced tomato, red onion, coriander and lime juice.', 'Slice chicken and assemble bowl with rice, beans, corn, guacamole and salsa.']), protein: 52, carbs: 62, fat: 14, photo_url: 'https://images.unsplash.com/photo-1512058454905-6b841e7ad132?w=800&q=80' },
];

function seed() {
  const db = getDb();
  
  console.log('Seeding nutrition tips...');
  const insertTip = db.prepare('INSERT OR IGNORE INTO nutrition_tips (category, title, content, is_featured) VALUES (?, ?, ?, ?)');
  for (const tip of TIPS) {
    insertTip.run(tip.category, tip.title, tip.content, 0);
  }
  console.log(`Seeded ${TIPS.length} tips`);

  console.log('Seeding meals...');
  const insertMeal = db.prepare('INSERT OR IGNORE INTO meal_ideas (name, calories, goal, emoji, photo_url, description, ingredients, method, protein, carbs, fat, is_active) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 1)');
  for (const meal of MEALS) {
    insertMeal.run(meal.name, meal.calories, meal.goal, meal.emoji, meal.photo_url, meal.description, meal.ingredients, meal.method, meal.protein, meal.carbs, meal.fat);
  }
  console.log(`Seeded ${MEALS.length} meals`);
}

seed();
